version: "3.9"
services:
  new_db:
    container_name: new_app_db
    image: postgres:11.11
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - new_db
    environment:
      LEGACY_DATABASE_HOST: legacy_app_db
      LEGACY_DATABASE_PORT: 5432
      LEGACY_DATABASE: legacy_app_development
      LEGACY_DATABASE_USER: postgres
      LEGACY_DATABASE_PASSWORD: password

networks:
  default:
    external:
      name: db_sync
