version: "3.9"
services:
  legacy_db:
    container_name: legacy_app_db
    image: postgres:11.10
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: password
  app:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - legacy_db
    environment:
      LEGACY_DATABASE_HOST: legacy_app_db
      LEGACY_DATABASE_PORT: 5433
      LEGACY_DATABASE: legacy_app_development
      LEGACY_DATABASE_USER: postgres
      LEGACY_DATABASE_PASSWORD: password

networks:
  default:
    external:
      name: db_sync
